version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: resetcomp
      TABLE_PREFIX: cres_
      WP_HOME: http://localhost:8080
      WP_SITEURL: http://localhost:8080/wp
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: resetcomp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3304:3306"

volumes:
  wordpress:
  db: